export interface WorkspaceTemplate {
  id: string;
  name: string;
  icon: string;
  description: string;
  category: 'marketing' | 'operacional' | 'reunioes' | 'relatorios';
  content: unknown[];
}

export const WORKSPACE_TEMPLATES: WorkspaceTemplate[] = [
  {
    id: 'briefing-campanha',
    name: 'Briefing de Campanha',
    icon: '📋',
    description: 'Estrutura completa para briefing de campanhas de marketing',
    category: 'marketing',
    content: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 1, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '📋 Briefing de Campanha', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Objetivo da Campanha', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Descreva o objetivo principal e as metas mensuráveis...', styles: { italic: true } }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Público-Alvo', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Faixa etária:', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Interesses:', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Comportamento de compra:', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Canais de Divulgação', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'Instagram', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'Facebook', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'WhatsApp', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'E-mail Marketing', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Cronograma', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Data de início: ', styles: { bold: true } }, { type: 'text', text: 'DD/MM/AAAA', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Data de término: ', styles: { bold: true } }, { type: 'text', text: 'DD/MM/AAAA', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Orçamento', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'R$ 0,00', styles: {} }],
        children: [],
      },
    ],
  },
  {
    id: 'playbook',
    name: 'Playbook Operacional',
    icon: '📖',
    description: 'Guia passo-a-passo para processos recorrentes',
    category: 'operacional',
    content: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 1, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '📖 Playbook: [Nome do Processo]', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'blue', textAlignment: 'left' },
        content: [{ type: 'text', text: '💡 Este playbook documenta o processo de [descrição]. Última atualização: [data].', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Visão Geral', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Descreva o objetivo deste processo e quando ele deve ser executado...', styles: { italic: true } }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Pré-requisitos', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Acesso à ferramenta X', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Permissão de Y', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Passo a Passo', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'numberedListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Primeiro passo...', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'numberedListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Segundo passo...', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'numberedListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Terceiro passo...', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Dicas e Observações', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'yellow', textAlignment: 'left' },
        content: [{ type: 'text', text: '⚠️ Atenção: [ponto de atenção importante]', styles: {} }],
        children: [],
      },
    ],
  },
  {
    id: 'ata-reuniao',
    name: 'Ata de Reunião',
    icon: '📝',
    description: 'Registro de reuniões com pauta e ações',
    category: 'reunioes',
    content: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 1, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '📝 Ata de Reunião', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [
          { type: 'text', text: 'Data: ', styles: { bold: true } },
          { type: 'text', text: '[DD/MM/AAAA]', styles: {} },
          { type: 'text', text: ' | Horário: ', styles: { bold: true } },
          { type: 'text', text: '[HH:MM]', styles: {} },
        ],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [
          { type: 'text', text: 'Participantes: ', styles: { bold: true } },
          { type: 'text', text: '@nome1, @nome2, @nome3', styles: {} },
        ],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Pauta', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'numberedListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Item 1 da pauta', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'numberedListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Item 2 da pauta', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Discussões', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Registre os principais pontos discutidos...', styles: { italic: true } }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Ações e Responsáveis', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'Ação 1 - @responsável - Prazo: DD/MM', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'Ação 2 - @responsável - Prazo: DD/MM', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Próxima Reunião', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Data: [DD/MM/AAAA] | Horário: [HH:MM]', styles: {} }],
        children: [],
      },
    ],
  },
  {
    id: 'relatorio-semanal',
    name: 'Relatório Semanal',
    icon: '📊',
    description: 'Template para relatórios semanais de performance',
    category: 'relatorios',
    content: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 1, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '📊 Relatório Semanal', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Semana: [DD/MM] a [DD/MM/AAAA]', styles: { bold: true } }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '✅ O que foi feito', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Entrega 1', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Entrega 2', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '📈 Métricas da Semana', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'KPI 1: [valor] (variação: +X%)', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'KPI 2: [valor] (variação: +X%)', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '🚧 Em andamento', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'bulletListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Projeto X - 60% concluído', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '📅 Próxima semana', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'Prioridade 1', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'checkListItem',
        props: { textColor: 'default', backgroundColor: 'default', textAlignment: 'left', checked: false },
        content: [{ type: 'text', text: 'Prioridade 2', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'heading',
        props: { level: 2, textColor: 'default', backgroundColor: 'default', textAlignment: 'left' },
        content: [{ type: 'text', text: '⚠️ Bloqueios / Riscos', styles: {} }],
        children: [],
      },
      {
        id: crypto.randomUUID(),
        type: 'paragraph',
        props: { textColor: 'default', backgroundColor: 'red', textAlignment: 'left' },
        content: [{ type: 'text', text: 'Liste aqui qualquer bloqueio ou risco identificado...', styles: { italic: true } }],
        children: [],
      },
    ],
  },
];

export const TEMPLATE_CATEGORIES = {
  marketing: { label: 'Marketing', color: 'bg-purple-500/10 text-purple-500' },
  operacional: { label: 'Operacional', color: 'bg-blue-500/10 text-blue-500' },
  reunioes: { label: 'Reuniões', color: 'bg-green-500/10 text-green-500' },
  relatorios: { label: 'Relatórios', color: 'bg-orange-500/10 text-orange-500' },
};
