import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      screens: {
        'xs': '375px',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        body: ['DM Sans', 'Inter', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        "border-subtle": "hsl(var(--border-subtle))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          glow: "hsl(var(--accent-glow))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          elevated: "hsl(var(--card-elevated))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          muted: "hsl(var(--sidebar-muted))",
        },
        brand: {
          yellow: "hsl(var(--brand-yellow))",
          red: "hsl(var(--brand-red))",
        },
        app: {
          gestao: "hsl(var(--app-gestao))",
          "gestao-glow": "hsl(var(--app-gestao-glow))",
          ia: "hsl(var(--app-ia))",
          "ia-glow": "hsl(var(--app-ia-glow))",
          ofertas: "hsl(var(--app-ofertas))",
          "ofertas-glow": "hsl(var(--app-ofertas-glow))",
          trade: "hsl(var(--app-trade))",
          "trade-glow": "hsl(var(--app-trade-glow))",
          dominio: "hsl(var(--app-dominio))",
          "dominio-glow": "hsl(var(--app-dominio-glow))",
          rh: "hsl(var(--app-rh))",
          "rh-glow": "hsl(var(--app-rh-glow))",
          reposicao: "hsl(var(--app-reposicao))",
          "reposicao-glow": "hsl(var(--app-reposicao-glow))",
          cd: "hsl(var(--app-cd))",
          "cd-glow": "hsl(var(--app-cd-glow))",
          cliente: "hsl(var(--app-cliente))",
          "cliente-glow": "hsl(var(--app-cliente-glow))",
          compras: "hsl(var(--app-compras))",
          "compras-glow": "hsl(var(--app-compras-glow))",
          academy: "hsl(var(--app-academy))",
          "academy-glow": "hsl(var(--app-academy-glow))",
          pmo: "hsl(var(--app-pmo))",
          "pmo-glow": "hsl(var(--app-pmo-glow))",
          comunidade: "hsl(var(--app-comunidade))",
          "comunidade-glow": "hsl(var(--app-comunidade-glow))",
          financeiro: "hsl(var(--app-financeiro))",
          "financeiro-glow": "hsl(var(--app-financeiro-glow))",
          loja: "hsl(var(--app-loja))",
          "loja-glow": "hsl(var(--app-loja-glow))",
          sorteios: "hsl(var(--app-sorteios))",
          "sorteios-glow": "hsl(var(--app-sorteios-glow))",
          console: "hsl(var(--app-console))",
          "console-glow": "hsl(var(--app-console-glow))",
        },
        /** @deprecated Use `app-*` instead. Backward-compat aliases. */
        module: {
          gestao: "hsl(var(--app-gestao))",
          "gestao-glow": "hsl(var(--app-gestao-glow))",
          ia: "hsl(var(--app-ia))",
          "ia-glow": "hsl(var(--app-ia-glow))",
          ofertas: "hsl(var(--app-ofertas))",
          "ofertas-glow": "hsl(var(--app-ofertas-glow))",
          trade: "hsl(var(--app-trade))",
          "trade-glow": "hsl(var(--app-trade-glow))",
          dominio: "hsl(var(--app-dominio))",
          "dominio-glow": "hsl(var(--app-dominio-glow))",
          rh: "hsl(var(--app-rh))",
          "rh-glow": "hsl(var(--app-rh-glow))",
          reposicao: "hsl(var(--app-reposicao))",
          "reposicao-glow": "hsl(var(--app-reposicao-glow))",
          cd: "hsl(var(--app-cd))",
          "cd-glow": "hsl(var(--app-cd-glow))",
          cliente: "hsl(var(--app-cliente))",
          "cliente-glow": "hsl(var(--app-cliente-glow))",
          compras: "hsl(var(--app-compras))",
          "compras-glow": "hsl(var(--app-compras-glow))",
          academy: "hsl(var(--app-academy))",
          "academy-glow": "hsl(var(--app-academy-glow))",
          pmo: "hsl(var(--app-pmo))",
          "pmo-glow": "hsl(var(--app-pmo-glow))",
          comunidade: "hsl(var(--app-comunidade))",
          "comunidade-glow": "hsl(var(--app-comunidade-glow))",
          financeiro: "hsl(var(--app-financeiro))",
          "financeiro-glow": "hsl(var(--app-financeiro-glow))",
          loja: "hsl(var(--app-loja))",
          "loja-glow": "hsl(var(--app-loja-glow))",
          sorteios: "hsl(var(--app-sorteios))",
          "sorteios-glow": "hsl(var(--app-sorteios-glow))",
          console: "hsl(var(--app-console))",
          "console-glow": "hsl(var(--app-console-glow))",
          works: "hsl(var(--app-gestao))",
        },
        // Festval Matte Architecture
        festval: {
          charcoal: "hsl(var(--festval-charcoal))",
          graphite: "hsl(var(--festval-graphite))",
          copper: "hsl(var(--festval-copper))",
          "copper-hover": "hsl(var(--festval-copper-hover))",
          "copper-subtle": "hsl(var(--festval-copper-subtle))",
          ivory: "hsl(var(--festval-ivory))",
          stone: "hsl(var(--festval-stone))",
          "stone-muted": "hsl(var(--festval-stone-muted))",
          border: "hsl(var(--festval-border))",
          "surface-elevated": "hsl(var(--festval-surface-elevated))",
          footer: "hsl(var(--festval-footer))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        elevated: "var(--shadow-elevated)",
        "glow-primary": "var(--shadow-glow-primary)",
        "glow-accent": "var(--shadow-glow-accent)",
      },
      transitionTimingFunction: {
        "out-expo": "var(--ease-out-expo)",
        "out-quart": "var(--ease-out-quart)",
        "in-out-quart": "var(--ease-in-out-quart)",
        "spring": "var(--spring)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          from: { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(8px)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
        "shimmer": {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "press": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(0.97)" },
          "100%": { transform: "scale(1)" },
        },
        // Aurora / Aceternity animations
        "aurora": {
          from: { backgroundPosition: "50% 50%, 50% 50%" },
          to: { backgroundPosition: "350% 50%, 350% 50%" },
        },
        "meteor": {
          "0%": { transform: "rotate(215deg) translateX(0)", opacity: "1" },
          "70%": { opacity: "1" },
          "100%": { transform: "rotate(215deg) translateX(-500px)", opacity: "0" },
        },
        "spotlight": {
          "0%": { opacity: "0", transform: "translate(-72%, -62%) scale(0.5)" },
          "100%": { opacity: "1", transform: "translate(-50%, -40%) scale(1)" },
        },
        "border-beam": {
          "100%": { offsetDistance: "100%" },
        },
        "gradient-flow": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s var(--ease-out-expo)",
        "fade-out": "fade-out 0.3s var(--ease-out-expo)",
        "scale-in": "scale-in 0.3s var(--ease-out-expo)",
        "slide-up": "slide-up 0.5s var(--ease-out-expo)",
        "slide-down": "slide-down 0.5s var(--ease-out-expo)",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "float": "float 4s ease-in-out infinite",
        "press": "press 0.15s ease-out",
        // Premium animations
        "aurora": "aurora 60s linear infinite",
        "meteor": "meteor 5s linear infinite",
        "spotlight": "spotlight 2s ease .75s 1 forwards",
        "border-beam": "border-beam calc(var(--duration)*1s) infinite linear",
        "gradient-flow": "gradient-flow 8s ease infinite",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
        "spin-slow": "spin-slow 8s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
